name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build persona3-hacker-rest
      run: docker build . --file Dockerfile --tag docker.io/brymlee1911/persona3-hacker-rest:$(date +%s)
